---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bash
  labels:
    app: bash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bash
  template:
    metadata:
      labels:
        app: bash
    spec:
      containers:
      - name: bash-container
        image: bash:4.2.53
        command: ['sleep', 'infinite']
        volumeMounts:
        - mountPath: /app
          name: my-pvc
  volumeClaimTemplates:
    - metadata:
        name: my-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi  # Size of the PVC
        storageClassName: ceph-rbd  # StorageClass
